apiVersion: v1
kind: Service
metadata:
  namespace: nyc-taxi
  labels:
    app: svc-debezium
  name: svc-debezium
spec:
  ports:
  - name: http
    port: 8083
    targetPort: 8083
  selector:
    app: debezium
