metadata:
  namespace: nyc-taxi

apiVersion: batch/v1
kind: Job
metadata:
  name: dbt-build
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: dbt
        image: nyc-dbt:k8s
        imagePullPolicy: IfNotPresent
        command:
        - "entrypoint-dbt"
        env:
        - name: DBT_PROFILES_DIR
          value: /opt/project/dbt
        - name: TRINO_HOST
          value: svc-trino
        - name: TRINO_PORT
          value: "8080"
        volumeMounts:
        - name: project-files
          mountPath: /opt/project
      volumes:
      - name: project-files
        persistentVolumeClaim:
          claimName: project-files-pvc
      resources:
        requests:
          cpu: 300m
          memory: 512Mi
        limits:
          cpu: 1
          memory: 1Gi
  backoffLimit: 3
