apiVersion: skaffold/v4beta3
kind: Config
manifests:
  helm:
    releases:
      - name: nyc-taxi
        chartPath: charts/nyc-taxi
        namespace: nyc-taxi
        valuesFiles: [charts/nyc-taxi/values.yaml]
build:
  local:
    push: false
  artifacts:
    - image: nyc-pipeline-tools
      context: .
      docker: { dockerfile: docker/tools.Dockerfile }
    - image: nyc-dbt
      context: .
      docker: { dockerfile: docker/dbt.Dockerfile }
    - image: nyc-airflow
      context: .
      docker: { dockerfile: docker/airflow.Dockerfile }
portForward:
  - resourceType: service
    resourceName: svc-superset
    namespace: nyc-taxi
    port: 8088
    localPort: 39080
  - resourceType: service
    resourceName: svc-minio
    namespace: nyc-taxi
    port: 9000
    localPort: 39081
  - resourceType: service
    resourceName: svc-minio
    namespace: nyc-taxi
    port: 9001
    localPort: 39086
  - resourceType: service
    resourceName: svc-kafka-ui
    namespace: nyc-taxi
    port: 8080
    localPort: 39082
  - resourceType: service
    resourceName: svc-spark-master
    namespace: nyc-taxi
    port: 8081
    localPort: 39083
  - resourceType: service
    resourceName: svc-trino
    namespace: nyc-taxi
    port: 8080
    localPort: 39084
  - resourceType: service
    resourceName: svc-airflow-webserver
    namespace: nyc-taxi
    port: 8080
    localPort: 39085
