metadata:
  namespace: nyc-taxi

apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-superset
  name: svc-superset
spec:
  ports:
  - name: http
    port: 8088
    targetPort: 8088
  selector:
    app: superset
