apiVersion: batch/v1
kind: Job
metadata:
  namespace: nyc-taxi
  name: cdc-seed
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: cdc-seed
        image: nyc-pipeline-tools:k8s
        imagePullPolicy: IfNotPresent
        command:
        - "entrypoint-cdc-seed"
        - "--input"
        - "/opt/project/data/raw/yellow_taxi/year=2024/month=01/yellow_tripdata_2024-01.parquet"
        - "--max-rows"
        - "5000"
        - "--dsn"
        - "postgresql://postgres:postgres@svc-postgres-cdc:5432/nyc_taxi"
        volumeMounts:
        - name: project-files
          mountPath: /opt/project
        - name: raw-data
          mountPath: /opt/project/data
      volumes:
      - name: project-files
        persistentVolumeClaim:
          claimName: project-files-pvc
      - name: raw-data
        persistentVolumeClaim:
          claimName: raw-data-pvc
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 1
          memory: 2Gi
  backoffLimit: 3
