apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-role
rules:
- apiGroups: ["", "batch", "apps"]
  resources: ["jobs", "pods", "pods/log", "services", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-rb
subjects:
- kind: ServiceAccount
  name: airflow-sa
roleRef:
  kind: Role
  name: airflow-role
  apiGroup: rbac.authorization.k8s.io
