metadata:
  namespace: nyc-taxi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-postgres-data
  labels:
    app: airflow-postgres
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
