apiVersion: v1
kind: Service
metadata:
  namespace: nyc-taxi
  name: svc-airflow-postgres
  labels:
    app: airflow-postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: airflow-postgres
  clusterIP: None
