connector.name=hive
hive.metastore=file
hive.metastore.catalog.dir=/data/trino-metastore
hive.allow-drop-table=true
hive.recursive-directories=true
hive.orc.use-column-names=true
hive.parquet.use-column-names=true
