apiVersion: v1
kind: Service
metadata:
  namespace: nyc-taxi
  labels:
    app: svc-spark-master
  name: svc-spark-master
spec:
  ports:
  - name: spark-rpc
    port: 7077
    targetPort: 7077
  - name: spark-webui
    port: 8081
    targetPort: 8081
  selector:
    app: spark-master
