apiVersion: v1
kind: Namespace
metadata:
  name: nyc-taxi
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: nyc-taxi
    meta.helm.sh/release-namespace: nyc-taxi
